version: 2.1

executors:
  notebook:
    docker:
      - image: circleci/python:3.7.0

jobs:
  rebuild-notebook:
    executor: notebook
    steps:
    - checkout
    - run:
        name: Install dependencies
        command: |
          sudo pip3 install -r requirements.txt
    - run:
        name: Rebuild notebook
        command: |
          make notebook
          # Ensures the generated images are matching
          git diff --color --exit-code

workflows:
  version: 2

  notebook:
    jobs:
      - rebuild-notebook
