version: 2.1

executors:
  charts:
    docker:
      - image: circleci/python:3.8.2

jobs:
  rebuild-charts:
    executor: charts 
    steps:
    - checkout
    - run:
        name: Install dependencies
        command: |
          sudo pip3 install -r requirements.txt
    - run:
        name: Rebuild notebook
        command: |
          # I accidentally deleted the source code for these charts :'(
          # rm -rf images/*
          make generate_charts
          # Ensures the generated images are matching
          git diff --color --exit-code

workflows:
  version: 2

  charts:
    jobs:
      - rebuild-charts
