version: 2.1

executors:
  base:
    docker:
      - image: cimg/base:2020.01
  notebook:
    docker:
      - image: circleci/python:3.7.0

jobs:
  rebuild-notebook:
    executor: notebook
    steps:
    - checkout
    - run:
        name: Install dependencies
        command: |
          sudo pip3 install -r requirements.txt
    - run:
        name: Rebuild notebook
        command: |
          make notebook
          # Ignore differences in the notebook
          git checkout -f notebooks/wasm-engines.ipynb
          # Ensures the generated images are matching
          git diff --color --exit-code
  run-wasm-engines:
    machine: true
    steps:
    - checkout
    - run:
        name: Run wasm-engines benchmark
        command: |
          make wasm_engines

workflows:
  version: 2

  notebook:
    jobs:
      - rebuild-notebook
  wasm-engines:
    jobs:
      - run-wasm-engines
