version: 2.1

executors:
  charts:
    docker:
      - image: circleci/python:3.7.0

jobs:
  build:
    executor: charts 
    steps:
    - checkout
    - run:
        name: Install dependencies
        command: |
          sudo pip3 install -r requirements.txt
    - run:
        name: Rebuild charts 
        command: |
          make generate_charts 
          # Ensures the generated images are matching
          git diff --color --exit-code

workflows:
  version: 2

  rebuild-charts:
    jobs:
      - build
